#!/bin/bash

squeue --me -o "%.20j %9i %9u %.2t %.12M %.20S %.11L %.10P %4C %5D %R %Z" \
| awk 'NR==1 {
           # print header row exactly as-is
           printf "%-20s %9s %9s %-2s %-12s %-20s %-11s %-10s %4s %5s %-20s %-20s\n",
                  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12
           next
       }
       {
           n=split($12,a,"/")
           # replace full path with basename
           printf "%-20s %9s %9s %-2s %-12s %-20s %-11s %-10s %4s %5s %-20s %-20s\n",
                  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,a[n]
       }'