#!/usr/bin/expect -f

set timeout 20
set username "<your-username>"
set password "<your-password>"
set scratch_dir "/home/$username/scratch.energybio"
set compress 0
set source_dir ""
set dest_dir ""

set argc [llength $argv]
set i 0
while {$i < $argc} {
	set arg [lindex $argv $i]
	switch -- $arg {
		"-x" {
			incr i
			set compress 1
		}
		"-f" {
			incr i
			set source_dir [lindex $argv $i]
		}
		"-o" {
			incr i
			set dest_dir [lindex $argv $i]
		}
		default {
			send_user "Unknown option: $arg\n"
		}
	}
	incr i
}

if {[string index $dest_dir 0] eq "/"} {
	set dest_path "$dest_dir"
} else {
	set dest_path "$scratch_dir/$dest_dir"
}

if {$compress eq 0} {
	send_user "Transferring files from $source_dir without compression"
	send_user "They will be copied by $username@login.zaratan.umd.edu to $dest_path"
	spawn rsync -avPh $source_dir $username@login.zaratan.umd.edu:$dest_path
}

if {$compress eq 1} {
        send_user "Transferring files from $source_dir with compression"
	send_user "They will be copied by $username@login.zaratan.umd.edu to $dest_path"
        spawn rsync -avzPh $source_dir $username@login.zaratan.umd.edu:$dest_path
}

# Wait for password prompt
expect "Password:"
send "$password\r"

# Wait for Duo prompt
expect "Passcode or option (1-2):"
send "1\r"

# Hand over control to user
interact       
