#!/bin/bash

COMPRESS=false
SOURCE_DIR=""
DEST_DIR="./"

usage() {
	echo "Usage: $0 -f <source_dir> [-o <destination_dir>] [-x]"
	echo ""
	echo "Required flags:"
	echo "  -f    Path to the file being copied relative to scratch.energybio"
	echo ""
	echo "Optional flags:"
	echo "  -o    Relative or absolute path to copy to on local machine"
	echo "  -z    Compress the files during transfer"
	echo "  -h    Show this help message"
	exit 1
}

while getopts "zf:o:h" opt; do
	case "${opt}" in
		z) COMPRESS=true;;
		f) SOURCE_DIR="${OPTARG}" ;;
		o) DEST_DIR="${OPTARG}" ;;
		h|*) usage ;;
	esac
done

shift $((OPTIND - 1))

# Enforce required inputs
if [ -z "${SOURCE_DIR}" ] ; then
	echo "Error: Missing Source Directory." >&2
	usage
fi

if $COMPRESS; then
	expect ~/bin/.from-zt.exp -z -f $SOURCE_DIR -o $DEST_DIR
else
	expect ~/bin/.from-zt.exp -f $SOURCE_DIR -o $DEST_DIR
fi
